apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: secure
  namespace: argocd
spec:
  description: Proyecto seguro con acceso restringido
  sourceRepos:
    - https://github.com/rcorderoayigroup/argo-demo.git
  destinations:
    - namespace: secure-ns
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Secret
    - group: apps
      kind: Deployment
