apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-hook
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: post-hook
          image: busybox
          command: ["sh", "-c", "echo Post deploy hook ejecutado"]
      restartPolicy: Never
